### ISSUE TITLE
4.26 Compilation failed

### ISSUE THREAD

**Issue by yinchonging** [tommybazar/TBRaymarchProject#3]
> Build started...
1>------ Build started: Project: TBRaymarchProject, Configuration: Development_Editor x64 ------
1>Using 'git status' to determine working set for adaptive non-unity build (D:\Unreal\TBRaymarchProject).
1>Building TBRaymarchProjectEditor...
1>Using Visual Studio 2019 14.28.29335 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333) and Windows 10.0.18362.0 SDK (C:\Program Files (x86)\Windows Kits\10).
1>[Adaptive unity build] Excluded from VolumeTextureToolkit unity file: ComputeVolumeTexture.cpp
1>Building 9 actions with 8 processes...
1>  [1/9] UE4Editor-Raymarcher-0002.lib
1>     Creating library D:\Unreal\TBRaymarchProject\Plugins\TBRaymarcherPlugin\Intermediate\Build\Win64\UE4Editor\Development\Raymarcher\UE4Editor-Raymarcher-0002.lib and object D:\Unreal\TBRaymarchProject\Plugins\TBRaymarcherPlugin\Intermediate\Build\Win64\UE4Editor\Development\Raymarcher\UE4Editor-Raymarcher-0002.exp
1>  [2/9] UE4Editor-TBRaymarchProject-0002.lib
1>     Creating library D:\Unreal\TBRaymarchProject\Intermediate\Build\Win64\UE4Editor\Development\TBRaymarchProject\UE4Editor-TBRaymarchProject-0002.lib and object D:\Unreal\TBRaymarchProject\Intermediate\Build\Win64\UE4Editor\Development\TBRaymarchProject\UE4Editor-TBRaymarchProject-0002.exp
1>  [3/9] UE4Editor-VolumeTextureToolkitEditor-0002.lib
1>     Creating library D:\Unreal\TBRaymarchProject\Plugins\TBRaymarcherPlugin\Intermediate\Build\Win64\UE4Editor\Development\VolumeTextureToolkitEditor\UE4Editor-VolumeTextureToolkitEditor-0002.lib and object D:\Unreal\TBRaymarchProject\Plugins\TBRaymarcherPlugin\Intermediate\Build\Win64\UE4Editor\Development\VolumeTextureToolkitEditor\UE4Editor-VolumeTextureToolkitEditor-0002.exp
1>  [4/9] UE4Editor-VolumeTextureToolkit-0002.lib
1>     Creating library D:\Unreal\TBRaymarchProject\Plugins\TBRaymarcherPlugin\Intermediate\Build\Win64\UE4Editor\Development\VolumeTextureToolkit\UE4Editor-VolumeTextureToolkit-0002.lib and object D:\Unreal\TBRaymarchProject\Plugins\TBRaymarcherPlugin\Intermediate\Build\Win64\UE4Editor\Development\VolumeTextureToolkit\UE4Editor-VolumeTextureToolkit-0002.exp
1>  [5/9] UE4Editor-TBRaymarchProject-0002.dll
1>     Creating library D:\Unreal\TBRaymarchProject\Intermediate\Build\Win64\UE4Editor\Development\TBRaymarchProject\UE4Editor-TBRaymarchProject-0002.suppressed.lib and object D:\Unreal\TBRaymarchProject\Intermediate\Build\Win64\UE4Editor\Development\TBRaymarchProject\UE4Editor-TBRaymarchProject-0002.suppressed.exp
1>  [6/9] UE4Editor-VolumeTextureToolkit-0002.dll
1>     Creating library D:\Unreal\TBRaymarchProject\Plugins\TBRaymarcherPlugin\Intermediate\Build\Win64\UE4Editor\Development\VolumeTextureToolkit\UE4Editor-VolumeTextureToolkit-0002.suppressed.lib and object D:\Unreal\TBRaymarchProject\Plugins\TBRaymarcherPlugin\Intermediate\Build\Win64\UE4Editor\Development\VolumeTextureToolkit\UE4Editor-VolumeTextureToolkit-0002.suppressed.exp
**1>Module.VolumeTextureToolkit.gen.cpp.obj : error LNK2019: unresolved external symbol "public: unsigned int __cdecl UVolumeTexture::CalcTextureMemorySize(int)const " (?CalcTextureMemorySize@UVolumeTexture@@QEBAIH@Z) referenced in function "public: virtual int __cdecl UVolumeTexture::CalcCumulativeLODSize(int)const " (?CalcCumulativeLODSize@UVolumeTexture@@UEBAHH@Z)
1>Module.VolumeTextureToolkit.gen.cpp.obj : error LNK2001: unresolved external symbol "public: virtual bool __cdecl UVolumeTexture::StreamOut(int)" (?StreamOut@UVolumeTexture@@UEAA_NH@Z)
1>Module.VolumeTextureToolkit.gen.cpp.obj : error LNK2001: unresolved external symbol "public: virtual bool __cdecl UVolumeTexture::StreamIn(int,bool)" (?StreamIn@UVolumeTexture@@UEAA_NH_N@Z)**
1>D:\Unreal\TBRaymarchProject\Plugins\TBRaymarcherPlugin\Binaries\Win64\UE4Editor-VolumeTextureToolkit-0002.dll : fatal error LNK1120: 3 unresolved externals
1>  [7/9] UE4Editor-VolumeTextureToolkitEditor-0002.dll
1>     Creating library D:\Unreal\TBRaymarchProject\Plugins\TBRaymarcherPlugin\Intermediate\Build\Win64\UE4Editor\Development\VolumeTextureToolkitEditor\UE4Editor-VolumeTextureToolkitEditor-0002.suppressed.lib and object D:\Unreal\TBRaymarchProject\Plugins\TBRaymarcherPlugin\Intermediate\Build\Win64\UE4Editor\Development\VolumeTextureToolkitEditor\UE4Editor-VolumeTextureToolkitEditor-0002.suppressed.exp
1>  [8/9] UE4Editor-Raymarcher-0002.dll
1>     Creating library D:\Unreal\TBRaymarchProject\Plugins\TBRaymarcherPlugin\Intermediate\Build\Win64\UE4Editor\Development\Raymarcher\UE4Editor-Raymarcher-0002.suppressed.lib and object D:\Unreal\TBRaymarchProject\Plugins\TBRaymarcherPlugin\Intermediate\Build\Win64\UE4Editor\Development\Raymarcher\UE4Editor-Raymarcher-0002.suppressed.exp
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets(46,5): error MSB3073: The command ""C:\Program Files\Epic Games\UE_4.26\Engine\Build\BatchFiles\Build.bat" TBRaymarchProjectEditor Win64 Development -Project="D:\Unreal\TBRaymarchProject\TBRaymarchProject.uproject" -WaitMutex -FromMsBuild" exited with code 6.
1>Done building project "TBRaymarchProject.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by tommybazar** [comment]
Project is still only 4.25 compatible. 

Seems like Epic _finally_ added  RenderTargetVolume in 4.26, so I'll have to rewrite some of the basic stuff to use that instead of my hacked ComputeVolumeTexture to use 4.26.
ETA ~1-2 weeks.

**Comment by tommybazar** [comment]
changes for 4.26 merged.
