### ISSUE TITLE
Consumption as a git submodule?

### ISSUE THREAD

**Issue by NAThompson** [tommybazar/TBRaymarchProject#5]
We consume only the `Plugins/TBRaymarcherPlugin` in our own project. However, we would like to consume this project as a `git submodule` to make consuming your updates easier.

Would it be possible to make the `Plugins/TBRaymarcherPlugin` directory it's own `git submodule` within this project, or is there a better idiom for consuming this plugin?

**Comment by tommybazar** [comment]
Yeah, I did want to get around to making the plugin a submodule, but never got around to it. 
Also my previous experience with submodules kind of discouraged me from doing it, it was always a hassle working with them :D

But yeah, as more people are actually starting to use this thing, it's probably the only viable way of nesting the plugin in a ready-to-use project.

I'll be pushing some major changes today and then going on a week's vacation, so maybe I'll get around to finally doing it at the end of next week.

Cheers, Tommy.

**Comment by NAThompson** [comment]
@tommybazar : No rush my friend. Have a nice vacation and thanks for the plugin.

**Comment by tommybazar** [comment]
Thanks.
If you have a VR headset, start plugging it in, you might need it later today ;)

**Comment by tommybazar** [comment]
Closing. As of today, TBRaymarcherPlugin is a submodule.
