### ISSUE TITLE
Fails when deploying to HoloLens2：Appxmanifestxml-missing

### ISSUE THREAD

**Issue by LBH023** [tommybazar/TBRaymarchProject#6]
Hi, I'm trying to deploy this project to HoloLens2 via Unreal, but I'm having trouble finding the Appxmanifest.xml file during the deployment process, so I'd like to ask you how to solve this problem for this project.
The following is the output log of some of the errors reported.

LogPlayLevel: Cleaning Stage Directory: D:\projects\TBRaymarchProject-master\Saved\StagedBuilds\HoloLens
LogPlayLevel: Copying NonUFSFiles to staging directory: D:\projects\TBRaymarchProject-master\Saved\StagedBuilds\HoloLens
LogPlayLevel: Copying UFSFiles to staging directory: D:\projects\TBRaymarchProject-master\Saved\StagedBuilds\HoloLens
LogPlayLevel: Copying DebugFiles to staging directory: D:\projects\TBRaymarchProject-master\Saved\StagedBuilds\HoloLens
LogPlayLevel: ********** STAGE COMMAND COMPLETED **********
LogPlayLevel: ********** PACKAGE COMMAND STARTED **********
LogPlayLevel: ********** PACKAGE COMMAND COMPLETED **********
LogPlayLevel: ********** DEPLOY COMMAND STARTED **********
LogPlayLevel: Registring D:\projects\TBRaymarchProject-master\Saved\StagedBuilds\HoloLens\AppxManifest.xml
LogPlayLevel: Error code: System.Exception: 无法打开包。
LogPlayLevel: 错误 0x80070002: 从位置 AppxManifest.xml 中打开文件失败，错误为: 系统找不到指定的文件。
LogPlayLevel: 。
LogPlayLevel: Error text: 错误 0x80070002: 从位置 AppxManifest.xml 中打开文件失败，错误为: 系统找不到指定的文件。
LogPlayLevel: 。
LogPlayLevel: Error: ERROR: 错误 0x80070002: 从位置 AppxManifest.xml 中打开文件失败，错误为: 系统找不到指定的文件。
LogPlayLevel:        。
LogPlayLevel:        (see C:\Users\22408\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+Program+Files+Epic+Games+UE_4.27\Log.txt for full exception trace)
LogPlayLevel: AutomationTool exiting with ExitCode=35 (Error_AppInstallFailed)
LogPlayLevel: Completed Launch On Stage: Deploy Task, Time: 20.799270
LogPlayLevel: BUILD FAILED

**Comment by tommybazar** [comment]
Unfortunately, don't have access to a HoloLens to test anything on it 🤷‍♀️
